### ISSUE TITLE
setlocale: LC_CTYPE

### ISSUE THREAD

**Issue by explosion-mental** [nsxiv/nsxiv#277] opened 2022-05-19 02:14 UTC
I noticed this while using vifm and opening a few images with sxiv. The order of the images is not the same as the vifm order (alphabetical, by name).

sxiv, and nsxiv use: LC_COLLATE

most suckless programs set it to per character with LC_CTYPE.
I don't know that deep about using locales, but using LC_CTYPE seems to be a good 'standard': meaning what most programs set and, hence, it will make more sense on those programs; say the order of a GUI file browser is one, but sxiv orders it differently.

**Comment by N-R-K** [comment] 2022-05-19 03:53
> I noticed this while using vifm and opening a few images with sxiv. The order of the images is not the same as the vifm order (alphabetical, by name).

duplicate of https://github.com/muennich/sxiv/issues/229 ?

**Comment by N-R-K** [comment] 2022-05-23 17:29
Closing since custom sorting is out of scope and all nsxiv currently does is respect the env's locale.

**Closed by N-R-K** 2022-05-23 17:29 UTC
