### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by timsofteng** [nsxiv/nsxiv#102] opened 2021-09-28 12:28 UTC
Please add wayland support.

**Comment by N-R-K** [comment] 2021-09-28 12:36
Hi, thanks for the feature request. `sxiv` codebase is pretty deeply integrated with X11 thus adding wayland support would mean making significant changes which should be considered out of our [project scope](https://github.com/nsxiv/nsxiv/blob/master/CONTRIBUTING.md#contribution-guideline).

If someone want's to work on a wayland port, then I think we can give him a separate repo under the `nsxiv` org.

**Comment by N-R-K** [comment] 2021-09-28 13:03
I'll keep the issue open so that it's visible to anyone who might be willing to work on a port.

**Comment by eylles** [comment] 2021-09-30 17:08
perhaps for this a look at the [imv](https://github.com/eXeC64/imv) codebase would be necesary along wrapping all the x11 specifics in such a way that the arguments sent to the fucntions can also be used by a wayland drawing library. 

as stated above this is well outside the project scope, but if anyone can and is willing to add wayland support the PR will be welcome for review.

**Comment by N-R-K** [comment] 2021-10-01 10:29
> if anyone can and is willing to add wayland support the PR will be welcome for review.

I don't think we should invite people to make PRs that might never get accepted. I'm failing to see how we can do native wayland support without heavy changes. And practically speaking, heavy changes also means new bugs and regressions.

*Maybe I'm wrong*, but I think a new repo for wayland port will be cleaner than trying to mold `sxiv` into supporting something it was ***never*** meant to support. X is literally engraved into the name of the software.

@guidocella Sorry for the ping, but since you're familiar with developing on wayland and seem to be a `sxiv` user, can you answer these questions real quick?

* Is my assumption that adding native support for wayland to `(n)sxiv` will require heavy rewrite wrong?
* How well does `(n)sxiv` work under xwayland? If there's small fixes we can do on our side (without being too invasive to the codebase) then I'm completely OK with that.

**Comment by guidocella** [comment] 2021-10-01 12:48
I don't have much experience with client-side Wayland development, but from quickly looking at sxiv's code it seems to me that only `window.c` and the `run` and key handling functions in `main.c` depend on X. You could use an alternative c file for just window.c when on Wayland. and update main.c to use the xkb API which works on both X and Wayland. As already suggested imitating imv's code is probably the best course of action.

Applications tend to run perfectly on Xwayland since it works by running a real X server, so no changes to nsxiv are necessary.

**Comment by eylles** [comment] 2021-10-01 19:10
so there's no problem with nsxiv as is in wayland, do u think there's a strong advantage or any improvement to be had from native wayland support, other than not requiring xwayland?

**Comment by guidocella** [comment] 2021-10-01 19:33
There are issues with XWayland if you use HiDPI scaling (https://github.com/swaywm/sway/issues/2966), but that doesn't matter for images, at most it affects sxiv's bar, whose font can be resized with Xresources anyway. Not requiring XWayland is pretty much the main advantage, and once the Wayland driver makes into wine I think it would be reasonable for many to want to uninstall XWayland, but as long as you need XWayland anyway I don't think Wayland support is a high priority, just nice-to-have.

**Comment by N-R-K** [comment] 2021-11-02 12:03
> from quickly looking at sxiv's code it seems to me that only window.c and the run and key handling functions in main.c depend on X.

From what I can tell imlib2 depends on X to render images. Closing this since that's out of our scope. If imlib2 adds wayland support then we can reopen it.

**Closed by N-R-K** 2021-11-02 12:03 UTC
Labels: wontfix
